### ISSUE TITLE
微信小程序开发工具预测结果正常，手机端预测异常

### ISSUE THREAD

**Issue by buaadf** [tensorflow/tfjs-wechat#10] opened 2019-07-15 03:54 UTC
TensorFlow.js version 1.2.2
tfjs-wechat plugin version 0.0.5
WeChat version 7.0.5
WeChat base API version 2.7.4
WeChat IDE version 1.02.1907052
Describe the problem or feature request 
使用tfjs在小程序端调用一个分割模型，在电脑端开发工具上可以得到正确的分割结果，但是在手机端（IOS和安卓）推断结果不正确，尝试了model.predict和model.execute，均存在此问题。另外，wx.createOffscreenCanvas()不支持真机调试
Code to reproduce the bug / link to feature request

**Comment by yichuxue** [comment] 2019-07-15 07:29
wx.createOffscreenCanvas() 这个方法不支持真机调试，微信官方文档有写。

**Comment by pyu10055** [comment] 2019-07-15 17:38
@buaadf  are there any error message generated in the debug console of the mobile devices?
There are couple possibilities where the inference could be different from the dev tool, can you try with
an image first if you have not done that?
Secondly, if you are using the camera API, can you verify the content of the frame is correct, and the size of the frame is what you expected.
Please let me know when you have tried those options.
thanks.

**Comment by buaadf** [comment] 2019-07-16 02:39
> wx.createOffscreenCanvas() 这个方法不支持真机调试，微信官方文档有写。

对，是不支持真机调试，但是支持预览

**Comment by buaadf** [comment] 2019-07-16 02:50
> @buaadf are there any error messages generated in the debug console of the mobile devices?
> There are couple possibilities where the inference could be different from the dev tool, can you try with
> an image first if you have not done that?
> Secondly, if you are using the camera API, can you verify the content of the frame is correct, and the size of the frame is what you expected.
> Please let me know when you have tried those options.
> thanks.

Thank you, I found that inference is correct on mobile devices which don't support webgl or webgl1 OES_texture_float, but much more slow (running on cup), however, on devices which support webgl and  OES_texture_float, the inference is wrong but fast, so I guess that on mobile devices the webgl is uncompleted, which can only support accelerate inference but the result is not accurate.

**Comment by buaadf** [comment] 2019-07-16 02:52
> @buaadf are there any error messages generated in the debug console of the mobile devices?
> There are couple possibilities where the inference could be different from the dev tool, can you try with
> an image first if you have not done that?
> Secondly, if you are using the camera API, can you verify the content of the frame is correct, and the size of the frame is what you expected.
> Please let me know when you have tried those options.
> thanks.

BTW, there's no error messages.

**Comment by pyu10055** [comment] 2019-07-16 03:42
@buaadf We have verified several models running correctly with webgl on wechat. If the cpu output is correct, sounds like the input is correct. If you can share your code, it will help us to reproduce the problem.

**Comment by buaadf** [comment] 2019-07-16 05:58
> @buaadf We have verified several models running correctly with webgl on wechat. If the cpu output is correct, sounds like the input is correct. If you can share your code, it will help us to reproduce the problem.

Sorry for that I can't share my code, but I have compared outputs of several mobilenet's layers on wechat dev-tool and on mobile phones(Xiaomi8, iphone 7p, iphoneX) with same input, and found that even the very first conv2d output is totally different.

**Comment by buaadf** [comment] 2019-07-16 06:06
@pyu10055 The output on HUAWEI P9 is correct, but much slower.

**Comment by pyu10055** [comment] 2019-07-16 06:16
Is it your model or the mobilenet converted from keras or TF saved model?

**Comment by buaadf** [comment] 2019-07-16 14:08
> Is it your model or the mobilenet converted from keras or TF saved model?

TF saved model

**Comment by pyu10055** [comment] 2019-07-16 14:38
Have you tried the example mobilenet demo mini app in the repo? 
Are there any differences between you app and the demo app?

**Comment by buaadf** [comment] 2019-07-17 04:04
@pyu10055 I tested the mobilenet demo, and set the input=tfc.ones([224, 224, 3]), print the output tensor, and found that the results on dev-tool and android device are different. I guess that's caused by the webgl float precision.

**Comment by pyu10055** [comment] 2019-07-17 05:48
@buaadf that is correct, the dev tool is full float, for example on iphone, it is half float.
It is not clear why in your setup both mobilenet and your model are not working, if you can share the your mobilenet test code would be great.

**Comment by pyu10055** [comment] 2019-07-19 17:27
@buaadf Want to circle back to see if you have figured out the original problem?

**Comment by kesyn** [comment] 2019-07-25 02:28
同样问题，运行posenet的demo时手机score一直非常低，于是抽出一张图存为数组或base64，在load完model后直接对这张图进行estimate，运行后模拟器score正常，pose的结果达到了0.2以上，各part的结果都在0.8以上，开启编译预览手机调试观察score围绕在0.06左右，part的score甚至低于0.01

**Comment by pyu10055** [comment] 2019-07-25 23:11
@kesyn is this for android or iOS?

**Comment by kesyn** [comment] 2019-07-26 00:26
@pyu10055 经测试，ios和安卓都发生了这样的情况，首先，当plugin.configPlugin不设置canvas时，模拟器，android，ios结果均正确，而设置canvas使用webgl后，结果发生了变化，ios的score降到0.06，android降至0.006，昨天更新的Nightly Build的IDE的通用设置里增加了开启GPU加速，设置开启或关闭后均是正确的结果。而手机输出几处tensor值，发现开启webgl后计算的值发生了一些变化，取了两处值的变化情况(均取变为数组后其中第一处不为0的数据)

1. posenet/posenet.ts内video取第一处不为0的值
模拟器开启与关闭gpu加速：[175, 161, 150]
ios开启与关闭webgl：[175, 161, 150] 
android开启与关闭webgl：[175, 161, 149]

2.@tensorflow-models/posenet/index.js padAndResizeTo(input, _a)内imageTensor.resizeBilinear后取第一处不为0的数据
模拟器开启gpu加速：[114, 106, 98]，关闭gpu：[113.52941131591797, 105.51557159423828, 97.5017318725586]
ios开启webgl:[113, 105, 97], 关闭webgl:[113.529.....,105.515.....,97.501.....]
android开启webgl[113.105.97],关闭webgl:[113.529.....,105.515.....,97.501.....]

**Comment by pyu10055** [comment] 2019-07-26 16:56
@kesyn Thank you for the detail report.
Since iOS only support half float, there will be some numeric difference. And usually these types of difference won't affect the model predict results.
Want to confirm with you, you are running with the latest code in this repo. I had some recent fixes that make the code compatible with the latest posenet API.
We have found some issues with Android, and we are looking into that. But in our test iOS is correct. What type of iPhone you are using that you see the lowering score?

**Comment by kesyn** [comment] 2019-07-26 18:52
Yes, the latest codes, iPhone X and mi Mix2

**Comment by kesyn** [comment] 2019-07-26 23:42
刚在8p上进行了测试，可以正常运行，所以可能是iOS 13的问题？

**Comment by kesyn** [comment] 2019-07-27 00:26
经过测试，确实是iOS13的问题，tfjs-models里的posenet的demo同样无法在iOS 13的safari里失败

**Comment by pyu10055** [comment] 2019-07-27 00:32
@kesyn @buaadf 
we have not tried iOS 13, thanks for the heads up.
We just fixed the android bug, maybe also would work for iOS 13. 
ref https://github.com/tensorflow/tfjs-core/pull/1858

Please try your mini app with the latest tfjs-core (version 1.2.6), and help to test all your phones. Thanks. :)

**Comment by yichuxue** [comment] 2019-07-27 04:08
@pyu10055 
The test results of several mobile phones are as follows:
wechat version: 7.0.5
tfjs-core version: 1.2.6
tfjs-converter version: 1.2.5
Iphone X(IOS 12.3) Result: Success
Iphone 8P(IOS 12.3) Result: Success
Iphone 7P(IOS 12.2) Result: Success
Iphone 7P(IOS 12.3.1) Result: Success
华为荣耀 imagic(Android 9)：Success
小米 9(MIUI 10 && Android 9)：Result: Error
小米 k20(MIUI 10 && Android 9): Result: Error
锤子坚果 pro(Android 7.1.1): Result: Error
vivi nex (Android ): Result: Error
小米 5X(Android 8.1): Result: Error

Error screenshot
![Screenshot_2019-07-27-12-07-42-943_com tencent mm](https://user-images.githubusercontent.com/21138081/61989809-2cb9b980-b067-11e9-95d0-c6f402af8b62.png)

**Comment by kesyn** [comment] 2019-07-27 04:54
1.2.6 is not working on iOS 13 either.

**Comment by pyu10055** [comment] 2019-07-27 05:42
Thanks, just to confirm, @kesyn is your test results on your phone for posenet the same as @yichuxue ?
@yichuxue it would be better to start a new issue for your ssd  model problem.

**Comment by kesyn** [comment] 2019-07-27 06:11
My Android is working :)

**Comment by yichuxue** [comment] 2019-07-27 06:14
@pyu10055 ok

**Comment by pyu10055** [comment] 2019-07-28 19:58
@kesyn can you help to file a bug with details on the failure of the iOS13 for safari at https://github.com/tensorflow/tfjs/issues?  thanks.

**Comment by kesyn** [comment] 2019-07-29 12:26
@pyu10055  今天我又重新测试了一下ios13 safari，目前https://github.com/tensorflow/tfjs-models/tree/master/posenet/demos这个demo直接运行在safari下失败，但是把build的js换成https://storage.googleapis.com/tfjs-models/demos/posenet/coco.c49bab0d.js这个在ios13内的safari内是可以成功，https://storage.googleapis.com/tfjs-models/demos/posenet/coco.html这个在线运行成功应该说是safari没有bug了

**Comment by kesyn** [comment] 2019-07-31 00:31
@pyu10055 Wechat posenet demo works on new update of iOS 13 beta 5

**Comment by pyu10055** [comment] 2019-08-01 00:13
@kesyn Thanks, good to know that, does safari demo works beta 5?

**Comment by kesyn** [comment] 2019-08-01 02:30
@pyu10055 Yes, it also works.

**Comment by pyu10055** [comment] 2019-08-07 20:25
Thanks @kesyn closing this issue since the problems have been resolved.

**Closed by pyu10055** 2019-08-07 20:25 UTC

**Comment by buaadf** [comment] 2019-08-08 03:18
Thanks really much for your work.
Sorry for the late reply, being stuck in lots of things recently.
All results are correct now, only that inference speed on ios (wechat) is really slow because offScreenCanvas works improperly on iOS, I guess.

**Comment by pyu10055** [comment] 2019-08-08 19:59
@buaadf offScreenCanvas should work on iOS, and actually we find models run much faster on iOS than Android. I am curious why you observe differently. If it really slow, it is possible that the webgl backend are not register correctly, you are running on CPU backend instead.

Maybe you can enable debug on the plugin config API, and check the console log see if the backend is `wechat-webgl`

```
plugin.configPlugin({
      fetchFunc: fetchWechat.fetchFunc(),
      tf, canvas: wx.createOffscreenCanvas()}, true);
```
