### ISSUE TITLE
Mobilenet demo how to get a score?

### ISSUE THREAD

**Issue by yichuxue** [tensorflow/tfjs-wechat#22] opened 2019-08-07 08:24 UTC
TensorFlow.js version：1.2.6
tfjs-wechat plugin version：0.05
WeChat version:7.0.5
WeChat base API version：2.7.7
WeChat IDE version：v1.02.1908012
Describe the problem or feature request

After running the mobilenet demo, I found his speed was around 80ms.

I used the demo in tfjs-example to run on chrome, and the predicted time is around 80ms, which is in line with my expectation.

However, after running the demo in tfjs-example on wechat, I found that my speed actually reached 800ms. The first time was 800ms, and the second time was about 200ms.

The demo in tfjs-example cannot improve my prediction speed. Is there a better way to improve the prediction speed of the model?

This is the result of tfjs-example on wechat.
![image](https://user-images.githubusercontent.com/21138081/62606381-b3f01280-b92e-11e9-9e4a-5ac5736279af.png)

This is the result on chrome.
![image](https://user-images.githubusercontent.com/21138081/62606828-97080f00-b92f-11e9-8f38-3925336d67da.png)

Code to reproduce the bug / link to feature request

**Comment by pyu10055** [comment] 2019-08-07 18:52
@yichuxue Just to understand your benchmark better, you are getting 80ms running the mobilenet demo of mini app and in mobile browser.
But you getting 200ms for which demo, and how are you running the demo? Did you build a mini app for that or just running it in the wechat browser?

**Comment by yichuxue** [comment] 2019-08-08 02:32
@pyu10055  I am running mobilenet model on mini app. Mobilenet_v1_0.5_224.

The reason for getting 200ms has been found out. On the mini app, I compiled and ran, so I only predicted once. Moreover, I did not warm up the model, so the predicted value was relatively high in the first time.

However, I encountered another problem, that is, the problem of android and ios platforms. On ios, my prediction results were very accurate and I could identify the objects I photographed, but on android, the results were completely wrong. After testing six android phones, only the glory magic was able to predict it properly.

Is there any solution for this at present?

**Comment by pyu10055** [comment] 2019-08-08 03:44
@yichuxue what is the version of tfjs-core you are using? As in other thread, we have fixed an issue related to android in the 1.2.6 release.

**Comment by yichuxue** [comment] 2019-08-08 04:32
@pyu10055 The tfjs-core version I'm using is 1.2.6.

**Comment by pyu10055** [comment] 2019-08-08 05:18
@yichuxue are you using wechat camera API or a static photo file? I would recommend you to use static photo first. I suspect it is input data issue, can you try to use canvas putImageData to display the input tensor, see if there are any differences between phones.

**Comment by yichuxue** [comment] 2019-08-08 13:05
@pyu10055 After testing, android identification error is indeed the cause of tfjs-core.
During the test process, get the image data from the android phone through canvas, and then save it as a file.
It then reads the image data saved as a file on ios and android, and predicts different results from the same code.

First, take an ios screenshot:
![R(}9 B YRVV(143IN3R6LJC](https://user-images.githubusercontent.com/21138081/62705276-a8c8df80-ba1f-11e9-940a-959fad145b1f.png)
![3U)VA_MOG`E%YPA@$G QI(2](https://user-images.githubusercontent.com/21138081/62705287-ae262a00-ba1f-11e9-8911-294dc2b644b8.png)
![O)HVHSTY5GU7XHM QMY`NN4](https://user-images.githubusercontent.com/21138081/62705296-b2eade00-ba1f-11e9-8840-0bb28844b7e0.png)


Then there's the android screenshot:
![D96FDD15BB147EE12D198164DE7CDE80](https://user-images.githubusercontent.com/21138081/62705338-c7c77180-ba1f-11e9-9e08-a073837c823d.jpg)
![3E846145BBE49A186FF4F31376BC9DCC](https://user-images.githubusercontent.com/21138081/62705356-d1e97000-ba1f-11e9-996f-e0cd93ef1b79.jpg)
![533FD9D9913F999FEC7E65CC281982D8](https://user-images.githubusercontent.com/21138081/62705358-d4e46080-ba1f-11e9-8290-65f685cec3cd.jpg)

**Comment by pyu10055** [comment] 2019-08-08 15:18
@yichuxue Thanks, if you can share you code, I can try to reproduce.

**Comment by yichuxue** [comment] 2019-08-09 03:21
@pyu10055 I uploaded the code and model to github.
`https://github.com/yichuxue/tf-temp.git`

**Comment by pyu10055** [comment] 2019-08-09 06:02
@yichuxue I tried your mini app, I am getting proper classification on my Pixel 2 (android) phone.
I will see if I can find a xiaomi or vivo phone tomorrow.

**Comment by yichuxue** [comment] 2019-08-09 06:09
@pyu10055 thanks.

**Comment by yichuxue** [comment] 2019-08-15 02:50
@pyu10055 Is there any new progress on this issue?

**Comment by yichuxue** [comment] 2019-08-18 03:40
> @pyu10055 After testing, The problem is prediction.
> During the test process, get the image data from the Android phone through canvas, and then save it as a file.
> It then reads the image data saved as a file on IOS and Android, and predicts different results from the same code.
> IOS got it right, Android got it wrong. Rose in the figure below is the correct prediction.
> 
> First, take an ios screenshot:
> Intercepted before 100.
> ![image](https://user-images.githubusercontent.com/21138081/62705754-a450f680-ba20-11e9-9e0b-01eb4c2f1894.png)
> ![image](https://user-images.githubusercontent.com/21138081/62705776-b5016c80-ba20-11e9-8946-2a7b6ca2577d.png)
> ![image](https://user-images.githubusercontent.com/21138081/62705804-c0549800-ba20-11e9-8bf6-f85dd6709181.png)
> 
> Then there's the android screenshot:
> Intercepted before 100.
> ![image](https://user-images.githubusercontent.com/21138081/62705837-d4989500-ba20-11e9-8a9b-4fcf1203efeb.png)
> ![image](https://user-images.githubusercontent.com/21138081/62705849-dbbfa300-ba20-11e9-92dd-b7fe4d93b9cc.png)
> ![image](https://user-images.githubusercontent.com/21138081/62705861-e37f4780-ba20-11e9-9ad3-cbb6e7a6ad57.png)

**Comment by pyu10055** [comment] 2019-08-23 20:34
@yichuxue I tried on Hwawei P20 and pixel 2, the predictions for mobilenet are correct.
Do you see issues on certain phones or all android devices?

**Comment by yichuxue** [comment] 2019-08-24 01:58
@pyu10055 I tested the phones of my colleagues in the department, and all the phones except huawei and iphone were mistaken.
Iphone X(IOS 12.3) Result: Success
Iphone 8P(IOS 12.3) Result: Success
Iphone 7P(IOS 12.3.1) Result: Success
华为荣耀 magic(Android 9)：Success
MI 9(MIUI 10 && Android 9)：Result: Error
Red MI k20(MIUI 10 && Android 9): Result: Error
锤子坚果 pro(Android 7.1.1): Result: Error
vivi nex (Android ): Result: Error
MI 5X(Android 8.1): Result: Error

**Comment by pyu10055** [comment] 2020-01-08 18:08
closing due to lack of activities.

**Closed by pyu10055** 2020-01-08 18:08 UTC
