### ISSUE TITLE
Posenet initialization error

### ISSUE THREAD

**Issue by yichuxue** [tensorflow/tfjs-wechat#24] opened 2019-08-09 07:00 UTC
TensorFlow.js version：1.2.7
tfjs-wechat plugin version：0.0.5
WeChat version：7.0.6
WeChat base API version：2.8.0
WeChat IDE version：v1.02.1908082
Describe the problem or feature request
Posenet initialization error

platform：windows 10

```
app.json

"tfjsPlugin": {
      "version": "0.0.5",
      "provider": "wx6afed118d9e81df9"
 }
```

`TypeError: this.fetchFunc is not a function`

Code to reproduce the bug / link to feature request

**Comment by pyu10055** [comment] 2019-08-10 03:48
@yichuxue please use plugin version 0.0.6

**Comment by yichuxue** [comment] 2019-08-10 04:01
@pyu10055 With version 0.0.6, the development tool no longer reports errors.
With version 0.0.6, the development tool no longer reports errors.
But the phone started reporting errors.
The error message is:
```
thirdScriptError
r.fetchFunc is not a function;at App lifeCycleMethod onLaunch function
TypeError: r.fetchFunc is not a function
```
```
thirdScriptError
Error: module "posent/@tensorflow/tfjs-core.js" is not defined
Error: module "posent/@tensorflow/tfjs-core.js" is not defined
```

**Comment by pyu10055** [comment] 2019-08-12 03:21
@yichuxue feels like your code has a typo:
can you share your repo? looks your code might have a typo:
posent/@tensorflow./tfjs-core.js
instead of posenet

**Comment by yichuxue** [comment] 2019-08-12 04:37
@pyu10055 I didn't change the code.
The case works well on a wechat IDE, but errors are reported on the phone.
```
/pages/index/index.ts
import * as posenet from '@tensorflow-models/posenet';
import {detectPoseInRealTime, drawPoses} from '../../posenet/posenet';
```

**Comment by pyu10055** [comment] 2019-08-13 16:12
@yichuxue Unfortunately, the issue is within WeChat camera API. The size of frame data of the back camera from the android phone are different from phone to phone. 
You will need to crop the image accordingly. 
cc @ele828 who is working on a fix for WeChat.

**Comment by yichuxue** [comment] 2019-08-14 02:15
@pyu10055 thanks.
The size of the camera is the size in example, which has not been modified.

**Comment by pyu10055** [comment] 2019-08-14 20:56
@yichuxue Thanks for the update, @ele828 any updates on the camera data size issue?

**Comment by yichuxue** [comment] 2019-08-15 02:49
@pyu10055 There is no update on camera data size from the current 2.8.0 update.

**Comment by pyu10055** [comment] 2020-01-08 18:08
closing due to lack of activities.

**Closed by pyu10055** 2020-01-08 18:08 UTC
