### ISSUE TITLE
TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by zhuweiyou** [tensorflow/tfjs-wechat#34] opened 2019-10-14 03:03 UTC
On Android devices：
```
TypeError: Right-hand side of 'instanceof' is not callable.
at t.fromPixels(https://usr/app-service.js:...)
```

TensorFlow.js version `1.2.7`
tfjs-wechat plugin version `0.0.6`
WeChat version `7.0.7`（but `Android WeChat 7.0.6` and `iOS devices` are ok）
WeChat base API version `2.7.5`
WeChat IDE version `2.7.5`

How can I fix this problem?

**Comment by pyu10055** [comment] 2019-10-15 16:01
@zhuweiyou can you provide the full stacktrace, and if possible please provide the sceenshot for the console log during the app start up. thanks.

**Comment by zhuweiyou** [comment] 2019-10-16 01:55
No other stacktrace.
The error should be caused by `tf.browser.fromPixels()`, but works fine in Android and IDE.

**Comment by pyu10055** [comment] 2019-10-16 23:47
@zhuweiyou do you have sample code that can help us to reproduce this problem? Thanks.

**Comment by zhuweiyou** [comment] 2019-10-18 06:28
This problem  may be caused by the `tfjs-models` library,  when `await model.classify(img)` is called.

Please see: https://github.com/tensorflow/tfjs-models/blob/master/mobilenet/src/index.ts#L205-L206

**Comment by zhuweiyou** [comment] 2019-10-23 02:03
Hi, this pull request work fine https://github.com/HunterXuan/wx-tfjs-demo/pull/11/files

**Comment by pyu10055** [comment] 2019-11-08 22:12
@zhuweiyou you might want to try the latest version of tensorflow.js 1.3.1, and feel like you are running on CPU backend instead of WebGL. Can you share your app console log? thanks

**Comment by pyu10055** [comment] 2020-01-08 18:09
closing due to lack of activities.

**Closed by pyu10055** 2020-01-08 18:09 UTC
